name: Pluginsenor
version: '${version}'
main: vorkubinks.pluginsenor.Pluginsenor
api-version: 1.19
commands:
  spawn:
    description: Command used to teleport back to spawn
    permission: spawn.use
  setspawn:
    description: Command used to set the spawn of the server
    permission: setspawn.use
  plugino.reload:
    description: Reloads the config.yml file
